global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - 'wger.rules'

scrape_configs:
  - job_name: caddy
    metrics_path: /metrics
    static_configs:
     - targets: [ 'caddy:2019' ]

  - job_name: django
    metrics_path: /prometheus/super-secret-path/metrics
    static_configs:
    - targets: ['web:8000']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]
